@type {import('tailwindcss').Config}
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#724d00",
        "outline-variant": "#bfc8c9",
        "on-surface-variant": "#3f484a",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#004f55",
        "error": "#ba1a1a",
        "primary": "#004349",
        "surface": "#fff9ee",
        "on-background": "#1e1b14",
        "primary-fixed-dim": "#8fd1d9",
        "error-container": "#ffdad6",
        "secondary": "#7f5600",
        "outline": "#6f797a",
        "secondary-fixed": "#ffddaf",
        "on-primary-fixed": "#002023",
        "on-error": "#ffffff",
        "inverse-surface": "#333028",
        "on-primary-container": "#90d2da",
        "on-secondary": "#ffffff",
        "primary-fixed": "#abeef6",
        "surface-dim": "#e0d9cd",
        "inverse-primary": "#8fd1d9",
        "background": "#fff9ee",
        "primary-container": "#0d5c63",
        "on-surface": "#1e1b14",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#281800",
        "secondary-container": "#ffbe4f",
        "tertiary-fixed": "#ffdad2",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#614000",
        "surface-variant": "#e8e2d5",
        "secondary-fixed-dim": "#fcbb4b",
        "tertiary-container": "#94311b",
        "tertiary": "#741a06",
        "surface-container": "#f4ede0",
        "on-tertiary-fixed-variant": "#832511",
        "inverse-on-surface": "#f7f0e3",
        "tertiary-fixed-dim": "#ffb4a3",
        "surface-bright": "#fff9ee",
        "surface-container-highest": "#e8e2d5",
        "on-error-container": "#93000a",
        "surface-container-low": "#faf3e6",
        "on-tertiary-container": "#ffb5a4",
        "on-tertiary-fixed": "#3d0600",
        "surface-tint": "#20686f",
        "surface-container-high": "#eee7db"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Domine", "serif"],
        "label-md": ["Karla", "sans-serif"],
        "display": ["Domine", "serif"],
        "body-lg": ["Karla", "sans-serif"],
        "headline-md": ["Domine", "serif"],
        "caption": ["Karla", "sans-serif"],
        "headline-lg": ["Domine", "serif"],
        "body-md": ["Karla", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}